Integrate Mayhem
mayhemheroes/micropython pull request #1
Opened 2022-05-18 06:43 UTC by rnshah9

2022-09-22 20:49 UTC, xansec requested changes
Hmm, this target doesn't quite look correct. I notice that it's crashing on every input: https://mayhem.forallsecure.com/rnshah9/mayhem-micropython/micropython/5. I don't think just sending fuzzed input to the python interpreter will work here. Is there a module that specifically parses input that we could fuzz instead? I'm thinking of something from here: http://docs.micropython.org/en/latest/reference/repl.html Please make the requested changes.

2022-10-03 01:23 UTC, rnshah9 commented
This project has a pretty complex build, so after spending a good amount time trying to build a fuzzer executable manually I decided to just replace the `main` function with the harness and reuse the project's build.

But `main.c` has a good amount of functionality that breaks the build if excluded, so I just copied the entire file (excl. `main`) into `fuzz_qstr_compute_hash.c`.

2022-10-03 17:44 UTC, xansec requested changes
Please make the requested changes.

2022-10-03 17:44 UTC, xansec commented on mayhem/Mayhemfile
> +project: micropython
We'll overwrite the image name here.

2022-10-03 17:44 UTC, xansec commented on mayhem/fuzz_qstr_compute_hash.c
> +#include <stdint.h>
Hmm, I don't necessarily love this approach, as we now have static copies of every function. If the `main.c` changes at all, how will those changes be propogated to this harness? Is there truly no way to run just the fuzzing functionality apart from the rest of the code (i.e. including/building libraries in Cmake/make style library dependencies?)

2022-10-09 02:42 UTC, rnshah9 commented on mayhem/fuzz_qstr_compute_hash.c
> +#include <stdint.h>
I agree it's suboptimal. One other option would be to edit `main.c` directly in this fork and let git handle the merging of upstream changes to the file.

Could you elaborate on "including/building libraries..."? Do you mean trying to build this project as a library?

2022-12-21 21:39 UTC, closed without merging

2022-12-21 21:40 UTC, xansec commented
Resolved with https://github.com/mayhemheroes/micropython/pull/2